version: '2'
services:
 victim:
  image: vergoh/vnstat:latest
  #cap_add:
  # - NET_ADMIN
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  networks:
   nointernet:
    ipv4_address: 172.18.77.77
 debian-attacker:
  image: giovprl/debian_attacker:latest
  stdin_open: true # docker run -i
  tty: true        # docker run -t
  networks: 
   nointernet:
    ipv4_address: 172.18.66.66


 bindrelay0:
  image: giovprl/bindrelay:zone_0
  networks: 
   nointernet:
    ipv4_address: 172.18.0.2
 bindrelay1:
  image: giovprl/bindrelay:zone_1
  networks: 
   nointernet:
    ipv4_address: 172.18.1.3
 bindrelay2:
  image: giovprl/bindrelay:zone_2
  networks: 
   nointernet:
    ipv4_address: 172.18.2.2



networks:
 nointernet:
  external: "false"
  ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1
